### ISSUE TITLE
Exception when signing in with empty fields

### ISSUE THREAD

**Issue by sszachow** [qczeq/FriendBook#1]
STEPS:
1. Open app.
2. Click sign in button with empty fields.

EXPECTED:
Application doesn't crash.

ACTUAL:
Application crashes:

System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=FriendBook
  StackTrace:
       at FriendBook.Models.UsersDictionary.UserExists(String userName) in \FriendBook-master\FriendBook-master\FriendBook\Models\UsersDictionary.cs:line 17
       at FriendBook.Utils.AuthService.CanAuthenticate(String userName, String password) in \FriendBook-master\FriendBook-master\FriendBook\Utils\AuthService.cs:line 16
       at FriendBook.ViewModels.PasswordViewModel.OnSignIn() in \FriendBook-master\FriendBook-master\FriendBook\ViewModels\PasswordViewModel.cs:line 33
  InnerException:

**Comment by qczeq** [comment]
Closed with commit https://github.com/qczeq/FriendBook/commit/5e1e56464764a0760d527b0b76a4730f9e2ae451
